version: '3.5'

services:

  jupyter:
    build: .
    image: jupyter
    container_name: jupyter
    ports:
      - "8888:8888"

    volumes:
      - type: bind
        source: ./notebooks
        target: /home/brent/.jupyter/notebooks
